### ISSUE TITLE
EliteChroma not starting correctly

### ISSUE THREAD

**Issue by Snyper1010** [poveden/EliteChroma#53] opened 2020-06-27 21:16 UTC
I have installed the latest version 1.8.0 and when I try to start in the start menu I get an error message which states ''EliteChroma was unable to identify all Elite:Dangerous related folders. Please choose from the following folders''

The window then closes down.

**Comment by Snyper1010** [comment] 2020-06-27 21:18
I have uninstalled and reinstalled and still getting the same issue

**Comment by poveden** [comment] 2020-06-28 20:58
@Snyper1010 Thank you for reporting the issue.

Could you please check the Windows Application Event Log just after the error message closes? Look for error entries with `.NET Runtime` as the event source.

Please let me know what you find (or not).

**Comment by Snyper1010** [comment] 2020-06-28 21:27
There is only one error showing. It doesn't state .NET as the source. I have attached the wer file for you to check if is there any info in there.

''Fault bucket 2235795716619257596, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: EliteChroma.exe
P2: 1.8.0.0
P3: 5ec598f1
P4: coreclr.dll
P5: 4.700.20.11803
P6: 5e4c6185
P7: c0000005
P8: 000000000006912c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD2F5.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6DE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6EF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6FC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD72C.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_EliteChroma.exe_5e3071c061c38bfd945f5ed5c69aba47c98c18af_bd2510d2_66e50679-f1e4-4a7a-9bbc-bc2ded16da10

Analysis symbol: 
Rechecking for solution: 0
Report Id: a453cf17-e688-48c9-98b3-24b3540191a1
Report Status: 268435456
Hashed bucket: e8b6c97e06e3031a6f07245bc76e46fc
Cab Guid: 0''

[Report.txt](https://github.com/poveden/EliteChroma/files/4843018/Report.txt)

**Comment by poveden** [comment] 2020-06-30 21:20
I'm afraid that the `Report.txt` you attached won't provide me with enough information, and I'm so far unable to reproduce your issue.

Can you confirm that:
- You are running Windows 10 64-bit? (it appears you do)
- You have .NET Core Desktop Runtime 3.1 (x64 version) installed? (it appears you have)
- You have the latest version of Razer Synapse 3 installed? (I cannot tell if you do)

With a "normal" crash, you should see the following entries in the Windows Application Event Log:
- A ".NET Runtime" error entry with event ID 1026
- An "Application Error" error entry with event ID 1000
- A bunch of "Windows Error Reporting" information entries with event ID 1001

The only reason (that I can think of) that may be causing that "APPCRASH" is an error coming from _outside_ the .NET code, and only if there's some misbehaving DLL.

Please install the latest versions of .NET and Synapse and try again. Tell me how it goes and, if it goes badly, come back to me with the installed versions numbers and _all_ the trace files you may gather.

Thank you very much in advance for helping me debug this issue.

**Comment by poveden** [comment] 2020-07-05 12:18
@Snyper1010 I've been doing some more tests, and I can confirm that `APPCRASH`es can be due to a misbehaved binding to an external DLL, like calling a function with an improper number of arguments, or passing an argument the wrong way.

EliteChroma does bind to some Windows DLLs, and the Colore library binds to the Razer Chroma SDK DLL. However, this starts to happen only _after_ the game folders are identified and we start to check if the game is running.

You mention that you see "unable to identify folders" message, and "then closes down". You mean it does it on its own, without you doing anything, or is that you click "OK" and then nothing else happens?

**Comment by Snyper1010** [comment] 2020-07-05 12:35
Hey, sorry I have been busy the last few days so hadn't had time to try things. 

I have just tried EliteChroma and got the same error message. But this time when I clicked 'Ok' it opened up a window to redirect the app to my ED game files. This wasn't happening before, the app was closing when I clicked ok on the error message. 

After redirecting the app to the correct drive EliteChroma began working immediately.

**Comment by poveden** [comment] 2020-07-06 22:50
I'm glad to see that it somehow has been "fixed" on its own. I'll nonetheless will add some tracing features to help on any issues that may arise in the future.

I'm closing this issue now. Please feel free to come back if you find any other issue or if you have any suggestions.

**Closed by poveden** 2020-07-06 22:50 UTC
