### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by Rovetown** [poveden/EliteChroma#81] opened 2020-12-25 12:35 UTC
So I'm using EDHM and wanted to try EliteChroma with my new BlackWidow Keyboard. But after the Application gave me the Window to choose the Location of ED (I've got it on Epic Games), it crashes as soon as I try to open the App. It is also not showing up in Synapse 3.

Even without EDHM it still crashed when i tried to start it, did several reinstallations.

**Comment by poveden** [comment] 2021-01-01 18:00
Hi @Rovetown, and Happy New Year! Thanks for reporting this. Could you please check the Windows Application Event Log just after EliteChroma closes? Look for error entries with .NET Runtime as the event source.

**Comment by Rovetown** [comment] 2021-01-02 11:02
[.NET Runtime.txt](https://github.com/poveden/EliteChroma/files/5760124/default.NET.Runtime.txt) - I couldnt find the specific GraphicsConfig file, but I searched every file related to that and nowhere was any missing xml code or anything. Maybe you can find the Location of that file so I can check if maybe something broke inside that.

**Comment by poveden** [comment] 2021-01-02 11:58
Seems to me a duplicate of #66.

This error is usually due to tampering with the `GraphicsConfigurationOverride.xml` file. This file is located under your Game Options folder, usually under `%LOCALAPPDATA%\Frontier Developments\Elite Dangerous\Options\Graphics`.

Can you confirm this is the case?

**Comment by Rovetown** [comment] 2021-01-02 12:48
[GraphicsConfigurationOverride.xml.txt](https://github.com/poveden/EliteChroma/files/5760244/GraphicsConfigurationOverride.xml.txt)
Thats my .xml - I edited it once, but reverted it back to the original one.

**Comment by poveden** [comment] 2021-01-02 13:01
The XML file you posted is OK. Is the issue still happening to you?

**Comment by Rovetown** [comment] 2021-01-02 13:01
Apparently the Game somehow decided to destroy my .xml, found the original code for it now it works, thanks. For anyone who has the same problem, the code looks like this: `<?xml version="1.0" encoding="UTF-8" ?>
<GraphicsConfig>
    <GUIColour>
        <Default>
            <LocalisationName>Standard</LocalisationName>
            <MatrixRed> 1, 0, 0 </MatrixRed>
            <MatrixGreen> 0, 1, 0 </MatrixGreen>
            <MatrixBlue> 0, 0, 1 </MatrixBlue>
        </Default>
    </GUIColour>
</GraphicsConfig>`

**Comment by poveden** [comment] 2021-01-02 13:10
Good to see that's working for you now. I'm closing this issue now. In any case, I'll make EliteChroma more resistant to these kind of issues when #67 is done.

Thanks again, and Happy New Year!

**Closed by poveden** 2021-01-02 13:10 UTC
