### ISSUE TITLE
EliteChroma not starting

### ISSUE THREAD

**Issue by Dbariri** [poveden/EliteChroma#70] opened 2020-11-24 23:40 UTC
## Summary

Elite Chroma not starting. No tray icon. No error messages.

## Crashlog

Cryptographic Services failed while processing the OnIdentity() call in the System Writer Object.

Details:
AddLegacyDriverFiles: Unable to back up image of binary WinQuic.

System Error:
The resource loader failed to find MUI file.

## Environment

- `EliteChroma` version: _1.9.0_
- .NET Core version: _3.1.10_
- Operating System: _Windows 10 Pro_
- Razer Synapse: _3.5.1030.101917_
- Razer Blackwidow X Chroma

**Comment by poveden** [comment] 2020-11-25 00:51
Hi @Dbariri! EliteChroma has nothing to do with cryptographic services, so it's not clear to me why you think this error message is related to EliteChroma.

Could you please check the Windows Application Event Log just after EliteChroma closes? Look for error entries with .NET Runtime as the event source.

**Comment by Dbariri** [comment] 2020-11-25 02:22
Hi @poveden ! That crashlog is the only error message that I found in Windows Application Event Log and it happened after installing EliteChroma. That is why I thought it could be related to it. There is no error entries with .NET Runtime as the event source.
When I run EliteChroma, nothing happens, no tray icon. Also nothing appears in the Task Manager.

**Comment by poveden** [comment] 2020-11-25 09:43
So this error came up while _installing_ EliteChroma? I'm using an off-the-shelf installer, so I don't have a clue of what may be happening.

I'd suggest to uninstall and install again EliteChroma, and try running it again. If it's still not running, and there are no ".NET Runtime" entries in your applications logs, then I fear you are facing an issue not related to EliteChroma.

Please try it and tell me how it goes.

**Comment by Dbariri** [comment] 2020-11-25 22:45
This is what I did:
1) uninstalled EliteChroma
2) uninstalled Razer Synapse
3) uninstalled Razer Chroma SDK
4) installed Synapse
5) installed SDK
6) installed EliteChroma
7) same crashlog appeared 

I have no clue where the problem is.

**Comment by poveden** [comment] 2020-11-26 00:23
You shouldn't need to install the SDK. Just installing Synapse 3 will do.

Also, remember to have the latest .NET Core **Desktop** Runtime (**x64**). Right now, that would be the [.NET 5.0 Desktop Runtime (v5.0.0) - Windows x64 Installer](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-5.0.0-windows-x64-installer).

Let's try a different approach:

1. Uninstall _just_ EliteChroma
2. Ensure that all of the above requirements are in place
3. Download the [EliteChroma 1.9.0 binaries' ZIP file](https://github.com/poveden/EliteChroma/files/5599752/EliteChroma-binaries-1.9.0.zip) and unzip it in any folder of your choosing
4. Run `EliteChroma.exe`

Tell me how it goes.

**Comment by Dbariri** [comment] 2020-11-27 00:24
I followed the steps above and got the same results.
No tray icon, nothing happens.
The only difference now is that there is no crashlog in the Windows Application Event Log.

**Comment by poveden** [comment] 2020-11-28 23:32
@Dbariri I've just published [version 1.9.1](https://github.com/poveden/EliteChroma/releases/tag/v1.9.1), which fixes an issue that may be related to yours. Please install it and tell me how it goes.

**Comment by Dbariri** [comment] 2020-11-30 22:04
I've installed the updated version 1.9.1 and got the same issue (no tray icon).
Also the same crashlog from my first post appeared in the Event Log.

**Comment by poveden** [comment] 2020-12-01 20:22
@Dbariri let's try something different: Please [download this ZIP file](https://github.com/poveden/EliteChroma/files/5211865/Sandbox.zip), unzip it in a folder of your choice, and run the `Sandbox.exe` program. It's a console application meant to test the keyboard mappings, but with a little luck it will expose the issue you are having.

Please tell me how it goes.

**Comment by poveden** [comment] 2020-12-02 20:58
@Dbariri  [Version 1.9.2](https://github.com/poveden/EliteChroma/releases/tag/v1.9.2) has been published, which also may apply to you. Please test it and tell me how it goes.

Also, please don't forget to do some tests with the ZIP file posted in my previous comment.

**Comment by Dbariri** [comment] 2020-12-03 00:31
I've installed version 1.9.2 and got no tray icon and the same crashlog in the Event log.
I also did the keyboard mapping test with the `Sandbox.exe`.
The only weird thing was the _left Ctrl_ that also blinked when I pressed _right Alt_.

**Comment by poveden** [comment] 2020-12-03 22:54
> The only weird thing was the _left Ctrl_ that also blinked when I pressed _right Alt_.

That's actually not weird: The `AltGr` key is equivalent to `Ctrl+Alt`. And the fact that `Sandbox.exe` worked means that the Razer SDK is correctly set up and that .NET can "talk" to it.

Let's try another thing: [Download this ZIP file](https://github.com/poveden/EliteChroma/files/5639415/EliteChroma-binaries-1.9.2-verbose.zip), and as before, please unzip it in a folder of your choosing and run `EliteChroma.exe`.

This version is the same 1.9.2, but with a couple of message boxes added. As soon as you run it, you should see a message box  saying "EliteChroma starting...". If there's any error running the application, you should see another message box, this time with a verbose error message. If it appears, please take a screen shot of it and share it with me.

**Comment by Dbariri** [comment] 2020-12-05 01:38
Nothing happened again. I mean, nothing at all !
No message boxes, no errors, nothing...

**Comment by poveden** [comment] 2020-12-05 09:06
@Dbariri I'm afraid that I cannot reproduce your issue. I even tried with another PC that didn't have anything installed, and it works for me.

[I've been looking around](https://www.google.com/search?q=windows+10+Cryptographic+Services+failed+while+processing+the+OnIdentity%28%29+call+in+the+System+Writer+Object.+Details%3A+AddLegacyDriverFiles%3A+Unable+to+back+up+image+of+binary+WinQuic.+System+Error%3A+The+resource+loader+failed+to+find+MUI+file.), and the error message you reported seems to be related to the Volume Shadow Copy Service (VSS). The error mentions `WinQUIC`, which is something I've never seen and seems a dependency of something else.

It seems to me that you have another software installed that's somehow conflicting with EliteChroma's execution.

I _might_ be able to help you, but it's something beyond the scope of EliteChroma. I don't really want to start asking you what kind of software you have installed on your PC, because I feel it would be very invasive of me, but if you feel like it, we can continue this conversation somewhere else.

**Comment by Dbariri** [comment] 2020-12-08 22:36
@poveden I have started Windows in Safe Mode and EliteChroma worked.
Both message box and tray icon appeared .
So, yes, there is some software conflicting with EliteChroma.
I have no problem to talk to you somewhere else.

**Comment by poveden** [comment] 2020-12-22 02:07
@Dbariri Please create an account at [Frontier Forums](https://forums.frontier.co.uk/categories/elite-dangerous/) (if you haven't one already), open [my forum's profile page](https://forums.frontier.co.uk/members/elrith.128412/) there, and start a conversation by clicking the aptly named "Start conversation" button. We can continue there.

I'm closing this issue now.

**Closed by poveden** 2020-12-22 02:07 UTC
