### ISSUE TITLE
Some keys are not being lighted-up

### ISSUE THREAD

**Issue by AstralDefender** [poveden/EliteChroma#161] opened 2023-04-17 11:56 UTC
For some reason on my keyboard Razer Ornata V2 most of the keys do not light up. For example, while in menu, only HOME, DEL, END, F10, SPACE, ESC and arrow keys are being light-up. While in game only 1-0 and some of other keys light's up, the "background" light is stuck on dark-yellow color.
Already tried re-installing the program, re-enabling it in Razer Chroma. Nothing helped.
Installed version: 1.18.0.0.

**Comment by poveden** [comment] 2023-05-22 00:27
Hi! Sorry for the late reply. Grown-up stuff, you know. 😛 

The main menu behaviour is partly by design, partly because the game doesn't signal whether you are seeing the main menu or not. Once you begin playing, it starts updating the files in the journal's folder, and this is what EliteChroma uses to do its job.

What version of Elite Dangerous are you running?

Can you confirm EliteChroma is running all the time? At the very least your keyboard should change when the game is in/out of focus or when it starts/closes. If not, maybe EliteChroma is silently crashing for some reason.

Can you share with me the contents of your options folder? Maybe there's some file that is being misinterpreted by EliteChroma.

**Comment by poveden** [comment] 2024-11-11 20:42
Hi @AstralDefender. I'm closing this issue as I don't have enough to reproduce it. Feel free to reopen it if it's still happening.

**Closed by poveden** 2024-11-11 20:42 UTC
