### ISSUE TITLE
Crash on game launch

### ISSUE THREAD

**Issue by billhedge** [poveden/EliteChroma#75] opened 2020-12-01 00:12 UTC
I haven't used EliteChroma in a while, so I installed 1.9.1 today. It's crashing as soon as the game launches (post-launcher). Here's the entry from the .NET Runtime in my event log:
Log Name:      Application
Source:        .NET Runtime
Date:          11/30/2020 6:59:54 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      [redacted]
Description:
Application: EliteChroma.exe
CoreCLR Version: 4.700.20.47201
.NET Core Version: 3.1.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteChroma.Core.Layers.BackgroundLayer.GetBackgroundColor(GameProcessState state, Double brightness) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Layers\BackgroundLayer.cs:line 68
   at EliteChroma.Core.Layers.BackgroundLayer.OnRender(ChromaCanvas canvas) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Layers\BackgroundLayer.cs:line 38
   at EliteChroma.Core.LayerBase.OnRender(ChromaCanvas canvas, Object state) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\LayerBase.cs:line 44
   at EliteChroma.Chroma.LayeredEffect.Render(IChroma chroma, Object state) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Chroma\LayeredEffect.cs:line 38
   at EliteChroma.Core.ChromaController.RenderEffect() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 238
   at EliteChroma.Core.ChromaController.GameState_Changed(Object sender, ChangeType e) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 207
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

If there's anything else I can provide to help figure this out, please let me know!

-Bill

**Comment by poveden** [comment] 2020-12-01 20:15
Hi @billhedge! Thanks for reporting this. I'm unable to reproduce your issue. EliteChroma will try to adjust some colors based on the game's color transform matrix, and it retrieves this information before doing anything else. The only way that this could happen is that EliteChroma is unable to obtain the transform matrix after a few retries.

Could you please share with me the following files?

- `%LOCALAPPDATA%\EliteChroma\Settings.json`
- `«GameInstallFolder»\GraphicsConfiguration.xml`
- `«GameOptionsFolder»\Graphics\GraphicsConfigurationOverride.xml`

**Comment by billhedge** [comment] 2020-12-01 20:26
Hi there, @poveden! Thanks for getting back to me. Here are the requested files.
[GraphicsConfiguration.xml.txt](https://github.com/poveden/EliteChroma/files/5625251/GraphicsConfiguration.xml.txt)
[Settings.json.txt](https://github.com/poveden/EliteChroma/files/5625253/Settings.json.txt)

GraphicsConfigurationOverride.xml is empty (0 bytes).

**Comment by poveden** [comment] 2020-12-01 20:48
I've pinpointed the issue. Your `GraphicsConfigurationOverride.xml` file _shouldn't_ be empty. I'll write a fix for this and will push it as soon as possible. I'll let you know when it's done.

**Comment by billhedge** [comment] 2020-12-01 20:54
Oh, well then. Oops! I guess that's what I get for messing around with custom colors and then deciding to go back to defaults. Sorry about that. Thanks for figuring it out so quickly!

**Comment by poveden** [comment] 2020-12-02 02:40
[Version 1.9.2](https://github.com/poveden/EliteChroma/releases/tag/v1.9.2) has been published.

@billhedge please test it and tell me how it goes.

**Comment by billhedge** [comment] 2020-12-02 03:01
@poveden it seems to work perfectly. I blanked out my GraphicsConfigurationOverride.xml and it worked like a charm! Thank you for the amazingly fast turnaround.

**Closed** 2020-12-02 17:28 UTC
Labels: bug
