### ISSUE TITLE
failed to recognize options folder 

### ISSUE THREAD

**Issue by imaginewaggons** [poveden/EliteChroma#126] opened 2021-10-13 03:15 UTC
## Summary

when i start elite chroma it says "elite chroma was unable to identify all Elite: dangerous-related folders. please choose the right folders in the following window". so i proceed to the next window and it says it does not recognize the options folder it puts a red x over the options line and when i go in and manually select the options folder it still put the red x on it 

## Steps to Reproduce

1. Go to 'start menu'
2. Click on 'EliteChroma'
3. See error
## Screenshots
![image](https://user-images.githubusercontent.com/92416296/137060562-f82b8cb3-1c56-4f91-b2aa-ec6c96ea2de0.png)
![image](https://user-images.githubusercontent.com/92416296/137060446-fd604bc0-d817-453b-93df-35182f42b1ae.png)
![image](https://user-images.githubusercontent.com/92416296/137060632-98a9ea17-4720-41d7-8dfa-0358fd2b24b3.png)
## Environment

- `EliteChroma` version: _1.14.0_
- .NET Core version: _(windowsdesktop-runtime-5.0.11-win-x64)_
- Operating System: _(Windows 10 pro)_

## Additional Context
please help I loved the chroma when playing before odyssey came out.

**Comment by imaginewaggons** [comment] 2021-10-17 17:55
![image](https://user-images.githubusercontent.com/92416296/137639093-0b704437-0877-422b-81b8-77b944b5b581.png)
this is the options sub folder

**Comment by poveden** [comment] 2021-10-17 21:09
Duplicate of #51.

I've been able to reproduce this. It seems that you're using the game with the default controls and no customization, and in that case the `Bindings` folder never gets created.

As a quick fix, do this in the game:

1. Go to _Options > Controls > General Controls_ (or any of the other categories; it doesn't matter)
2. Pick any other preset listed in the _Presets_ drop-down list, and click _Apply_
3. Open again the same control category, select the preset you previously had, and click _Apply_

This will create the `Bindings` folder for you with the `StartPreset.start` file in it. Please confirm if this works out for you.

I will track this bug on issue #55.

**Comment by poveden** [comment] 2021-10-17 21:10
Duplicate of #51.

**Closed** 2021-10-30 01:01 UTC
Labels: duplicate
